#ifndef STABLE_H
#define STABLE_H

// Speed up compilation by adding common, infrequently changed headers here

#include <algorithm>
#include <array>
#include <assert.h>
#include <atomic>
#include <cassert>
#include <cerrno>
#include <chrono>
#include <clocale>
#include <cmath>
#include <codecvt>
#include <condition_variable>
#include <crash_handler.h>
#include <cstdarg>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <DbgHelp.h>
#include <deque>
#include <exception>
#include <fcntl.h>
#include <float.h>
#include <functional>
#include <future>
#include <global_utilities.h>
#include <initializer_list>
#include <inttypes.h>
#include <iomanip>
#include <iostream>
#include <limits>
#include <limits.h>
#include <list>
#include <lmcons.h>
#include <locale>
#include <logger.h>
#include <map>
#include <math.h>
#include <memory>
#include <memory.h>
#include <mutex>
#include <opencv/cv.h>
#include <opencv2/core/core.hpp>
#include <ostream>
#include <QAbstractItemModel>
#include <QAbstractVideoSurface>
#include <QApplication>
#include <QBoxLayout>
#include <QBrush>
#include <QBuffer>
#include <QByteArray>
#include <QCamera>
#include <QCameraInfo>
#include <QCheckBox>
#include <QClipboard>
#include <QCloseEvent>
#include <QColor>
#include <QColorDialog>
#include <qcolordialog.h>
#include <QCommandLineParser>
#include <QCoreApplication>
#include <QCryptographicHash>
#include <QCursor>
#include <QDataStream>
#include <QDateTime>
#include <QDebug>
#include <QDesktopServices>
#include <QDesktopWidget>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDir>
#include <QDirIterator>
#include <QDrag>
#include <QDragEnterEvent>
#include <QDropEvent>
#include <QElapsedTimer>
#include <QEvent>
#include <QEventLoop>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFocusEvent>
#include <QFont>
#include <QFontMetrics>
#include <QFuture>
#include <QFutureSynchronizer>
#include <QFutureWatcher>
#include <QGesture>
#include <QGestureEvent>
#include <QGraphicsOpacityEffect>
#include <QGuiApplication>
#include <QHash>
#include <qheaderview.h>
#include <QImage>
#include <QImageReader>
#include <QImageWriter>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QLabel>
#include <qline.h>
#include <QLineEdit>
#include <QList>
#include <QListWidget>
#include <QListWidgetItem>
#include <QLocale>
#include <QLocalServer>
#include <QLocalSocket>
#include <QLoggingCategory>
#include <QMainWindow>
#include <QMap>
#include <qmath.h>
#include <QMatrix4x4>
#include <QMediaPlayer>
#include <QMediaPlaylist>
#include <QMenu>
#include <QMessageBox>
#include <QMetaEnum>
#include <QMetaObject>
#include <QMimeData>
#include <QMouseEvent>
#include <QMovie>
#include <QMutex>
#include <QMutexLocker>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QObject>
#include <QOffscreenSurface>
#include <QOpenGLBuffer>
#include <QOpenGLContext>
#include <QOpenGLFramebufferObject>
#include <QOpenGLFunctions>
#include <QOpenGLPaintDevice>
#include <QOpenGLShaderProgram>
#include <QOpenGLTexture>
#include <QOpenGLWidget>
#include <QPainter>
#include <qpainter.h>
#include <QPainterPath>
#include <QPair>
#include <QParallelAnimationGroup>
#include <QPen>
#include <QPixmap>
#include <QPlainTextEdit>
#include <QPoint>
#include <qpoint.h>
#include <QPointer>
#include <QPointF>
#include <QPolygonF>
#include <QPrintDialog>
#include <QPrinter>
#include <QProcess>
#include <QProcessEnvironment>
#include <QPropertyAnimation>
#include <QProxyStyle>
#include <QPushButton>
#include <QQuaternion>
#include <QQueue>
#include <QRect>
#include <QRectF>
#include <QRegExp>
#include <QResizeEvent>
#include <QRunnable>
#include <QScopedPointer>
#include <QScreen>
#include <QScrollbar>
#include <QScroller>
#include <QSequentialAnimationGroup>
#include <QSettings>
#include <QSharedDataPointer>
#include <qsharedpointer>
#include <QSharedPointer>
#include <QSlider>
#include <QSpinBox>
#include <QStack>
#include <QStandardItemModel>
#include <QstandardPaths>
#include <QStandardPaths>
#include <qstandardpaths.h>
#include <QStateMachine>
#include <QStatusBar>
#include <QString>
#include <QStringList>
#include <QStyle>
#include <QStyleOption>
#include <QSvgRenderer>
#include <QSysInfo>
#include <qt_windows.h>
#include <QTableWidget>
#include <QTapAndHoldGesture>
#include <QtConcurrent>
#include <QtConcurrentRun>
#include <QtCore/qglobal.h>
#include <QTemporaryFile>
#include <QTextEdit>
#include <QTextStream>
#include <QThread>
#include <QThreadPool>
#include <QTime>
#include <QTimer>
#include <QtMath>
#include <QTouchEvent>
#include <QTransform>
#include <QTranslator>
#include <QtTest/QtTest>
#include <QtWebSockets/QWebSocket>
#include <QtWidgets>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include <QUrl>
#include <QUuid>
#include <QValidator>
#include <QVariant>
#include <QVector>
#include <QVector2D>
#include <QVector3D>
#include <QVector4D>
#include <qvector4d.h>
#include <QVideoFrame>
#include <QVideoSurfaceFormat>
#include <QVideoWidget>
#include <QWaitCondition>
#include <QWhatsThis>
#include <QWidget>
#include <qwidget.h>
#include <QWindow>
#include <QXmlStreamWriter>
#include <set>
#include <settings.h>
#include <share.h>
#include <single_instance.h>
#include <stack>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdexcept>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <sys/stat.h>
#include <sys/types.h>
#include <system_error>
#include <thread>
#include <time.h>
#include <tlhelp32.h>
#include <typeinfo>
#include <unordered_map>
#include <utility>
#include <vector>

#ifdef Q_OS_WIN
#include <WinBase.h>
#include <windows.h>
#include <Windows.h>
#endif


#endif // STABLE_H
